spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000 # 連接超時
            read-timeout: 2000 # 讀取超時
          server-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true
feign:
  sentinel:
    enabled: true